import type { Metadata } from "next";
import { Comic_Neue, Inter, Open_Sans, Saira } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sans.className}>
         <Toaster position="top-center" />
        <Providers >
          {children}
        </Providers>
      </body>
    </html>
  );
}
