import type { Metadata } from "next";
import { Comic_Neue, Inter, Open_Sans, Saira } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";
import PlausibleProvider from "next-plausible";
import { ThemeProvider } from "@/components/theme/theme-provider";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <script defer data-domain="" src="https://plausible.io/js/script.js"></script> */}
      <head>
        <PlausibleProvider
          domain="yournextsass.vercel.app"
          taggedEvents={true}
        />
      </head>
      <body className={sans.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="top-center" />
          <Providers>{children}</Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
