import type { Metadata } from "next";
import { Comic_Neue, Inter, Open_Sans, Saira } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";
import PHProvider from "@/components/Analaytics-Provider";
import PlausibleProvider from "next-plausible";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <script defer data-domain="" src="https://plausible.io/js/script.js"></script> */}
      <PlausibleProvider domain="https://yournextsass.vercel.app">
      <body className={sans.className}>
         <Toaster position="top-center" />
        <Providers >
          {children}
        </Providers>
      </body>
      </PlausibleProvider>
    </html>
  );
}
